services:
  validacion-formularios:
    image: nginx:alpine
    restart: always

    volumes:
      - ./:/usr/share/nginx/html:ro

    expose:
      - "80"

    environment:
      VIRTUAL_HOST: validacion.docker.sulbaranjc.com
      VIRTUAL_PORT: "80"

    networks:
      - internal
      - nginx-proxy

networks:
  internal:
    name: validacion_formularios_internal

  nginx-proxy:
    external: true
